plugins {
    id 'com.android.application'
}

android {
    namespace 'me.hisset.mali'
    compileSdk 35

    defaultConfig {
        applicationId 'me.hisset.mali'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            debuggable false
        }
        release {
            minifyEnabled false
        }
    }
}
